services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped

  tor:
    image: osminogin/tor-simple:latest
    container_name: tor-proxy
    restart: unless-stopped
    ports:
      - "9050:9050"
